name: CI
on: 
  push: 
    branches: 
      - main
jobs:
  main: 
    runs-on: ubuntu-latest
    steps:
      - name: Print a Welcome Message
        run: echo "Hello World! from our first Github Actions Workflow!"
        
      - name: Checkout repository
        uses: actions/@checkout/v4.2.2

      - name: list repository files
        run: ls -la
